# Generated by Django 3.1.5 on 2021-01-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(max_length=17)),
                ('ssid', models.CharField(max_length=256)),
                ('vendor', models.CharField(max_length=256)),
                ('band', models.CharField(default=None, max_length=8)),
                ('channel', models.CharField(max_length=8)),
                ('rates', models.CharField(max_length=256)),
                ('rssi', models.IntegerField()),
                ('security', models.CharField(max_length=256)),
                ('timestamp', models.IntegerField()),
                ('width', models.CharField(max_length=8)),
                ('geolocation', models.JSONField()),
            ],
        ),
    ]
