# Generated by Django 3.1.5 on 2021-01-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation_api', '0002_georesults_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georesults',
            name='frequency',
            field=models.IntegerField(default=None),
        ),
    ]
