# Generated by Django 3.1.5 on 2021-01-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation_api', '0003_auto_20210120_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georesults',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
